spring.application.name=petcare-platform
server.port=${PORT:8081}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/petcare_platform}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://127.0.0.1:5173,http://localhost:5173}
